version: '3.4'

services:
  db:
    image: mysql:5.7.27
    command: mysql --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    volumes:
      - type: bind
        source: ./DBBackup/backup.sql
        target: /docker-entrypoint-initdb.d/backup.sql
    ports:
      - "51925:3306"
      - "44374:443"
    networks:
      - udemy-networks

  restwithaspnetu:
    image: restwithaspnetu-api
    build:
      context: .
      dockerfile: RestWithASPNETU/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44374
    ports:
      - "51925:80"
      - "44374:443"
    networks:
      - udemy-networks

networks:
  udemy-networks:
    driver: bridge